configName: ATSAMD21J18A
folderName: hid_touchpad_usart_sam_d21_xpro
format_version: v1.0
frameworkPath: ..\..\Harmony3
processor: ATSAMD21J18A
projectName: hid_touchpad_usart_sam_d21_xpro
settings:
  PackageFilter: bootloader;bootloader_apps_serial_memory;bootloader_apps_uart;bootloader_apps_usb;bsp;core;core_apps_sam_d21_da1;crypto;csp;csp_apps_sam_d21_da1;dev_packs;net;quick_docs;reference_apps;usb;usb_apps_device;usb_apps_dual_role;usb_apps_host;usb_apps_multi_controller
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMD21_DFP\3.4.116\samd21a\atdf\ATSAMD21J18A.atdf
